### ISSUE TITLE
Is there a way to import just a single file from "client"?

### ISSUE THREAD

**Issue by cakoose** [arantespp/monorepo-example#5]
I'm trying to set up a project and your example has been helpful.

However, I ran into an issue: I'm going to have a lot of shared code and would like to be able to import just a single file from the shared workspace.

In your example, you do:

```typescript
import Foo from 'client';
```

I tried (1) creating a new file "client/src/blah.ts" and importing from "cmd/src/index.ts":

```typescript
import { BLAH } from 'client/blah';  // ERROR: Cannot find module 'client/blah'
```

Do you know how to solve this problem?

**Comment by arantespp** [comment]
Hello @cakoose! I'm very happy that one of my repositories are helping you. 

Considering I understood your question well, I created an example in [a new repository](https://github.com/ttoss/monorepo/tree/cakoose-example) that I'm using for my monorepo tests.

So I have a [file](https://github.com/ttoss/monorepo/blob/cakoose-example/packages/client/cra/src/App.tsx) that imports some modules of my lib in three different ways.

```
// import { randomSquareNumber } from '@lib/magic-number';
// import { randomSquareNumber } from '@lib/magic-number/src/randomSquareNumber';
import { randomSquareNumber } from '@lib/magic-number/randomSquareNumber';
```

The first import directory `@lib/magic-number` exports other modules than `randomSquareNumber` and the other two, export only `randomSquareNumber`.

In my [magic number lib](https://github.com/ttoss/monorepo/tree/cakoose-example/packages/lib/magic-number), I have:

- the `src/` folder that has all methods;
- the `index.ts` file which exports all public methods;
- the `randomSquareNumber.ts` that exports only `src/randomSquareNumber.ts`.

Because of these three, I can import `randomSquareNumber` in those three ways above.

**Comment by cakoose** [comment]
Thanks for looking into this!

The one remaining problem is I would like the code in my library to be under "src", but doing that means you have to include "src" in the import.  Just importing "@lib/magic-number/randomSquareNumber" doesn't work, right?

**Comment by cakoose** [comment]
Also, it looks like any sub-project can import any of the NPM dependencies, even if they're not in the sub-project's own "packages.json".  Is that correct?

(One of the reasons I wanted to split into sub-projects was to keep my dependencies clean, e.g. not accidentally import a Node package in client code.)

**Comment by cakoose** [comment]
Thanks again for the info!  Maybe I'll just go back to having a single top-level "package.json" for now :-)

BTW, it looks like Yarn 2 is more strict with dependencies ([link](https://yarnpkg.com/features/workspaces#what-does-it-mean-to-be-a-workspace)):

> Only the dependencies depended upon by a workspace can be accessed. Said another way, we strictly enforce your workspaces dependencies.

Unfortunately I ran into a bunch of compatibility issues with when I tried Yarn 2 -- probably stuff that will be ironed out as it gets more usage.
